#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

HOST = data.get('host')

zitadel_app_config = {
    "ZITADEL_EXTERNALDOMAIN": HOST,
    "ZITADEL_EXTERNALPORT": "443",
    "ZITADEL_EXTERNALSECURE": "true",
}
agent.write_envfile("zitadel-app.env", zitadel_app_config)
#agent.dump_env()
